# Generated by Django 4.2.7 on 2026-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('aadhaar_mobile', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('attendee_type', models.CharField(max_length=30)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('meal_preference', models.CharField(max_length=20)),
                ('parking_facility', models.CharField(max_length=20)),
                ('heard_about', models.CharField(blank=True, max_length=50, null=True)),
                ('special_requirement', models.TextField(blank=True, null=True)),
                ('photo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_base64', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='REGISTERED', max_length=20)),
                ('meal_taken', models.BooleanField(default=False)),
                ('parking_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_management',
            },
        ),
    ]
