# Generated by Django 4.2.7 on 2026-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('attendee_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('meal_preference', models.CharField(blank=True, max_length=20, null=True)),
                ('parking_facility', models.CharField(blank=True, max_length=5, null=True)),
                ('heard_about', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requirement', models.TextField(blank=True, null=True)),
                ('photo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_base64', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='REGISTERED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_management',
                'ordering': ['-created_at'],
            },
        ),
    ]
