# Generated by Django 4.2.7 on 2026-04-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
